# Generated by Django 3.2.9 on 2021-12-06 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SensorApp', '0002_alter_ultrasonicsensor_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ultrasonicsensor',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='ultrasonicsensor',
            name='updated_at',
        ),
    ]
