# Generated by Django 3.2.9 on 2021-12-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SensorApp', '0003_auto_20211206_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ultrasonicsensor',
            name='distance',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
    ]
