# Generated by Django 3.2.9 on 2021-12-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SensorApp', '0005_auto_20211227_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='AZDeliveryCamera', max_length=50)),
                ('description', models.TextField()),
                ('pin', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UltrasonicSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='HC-SR04', max_length=50)),
                ('description', models.TextField()),
                ('pin', models.IntegerField()),
                ('distance', models.DecimalField(decimal_places=4, max_digits=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UltrasonicSensorDetail',
        ),
        migrations.DeleteModel(
            name='UltrasonicSensorMaster',
        ),
    ]
