# Generated by Django 4.0 on 2021-12-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SensorApp', '0006_auto_20211227_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camerasensor',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='camerasensor',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ultrasonicsensor',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ultrasonicsensor',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
