# Generated by Django 3.2.9 on 2021-12-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SensorApp', '0007_alter_camerasensor_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='lcdSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pin', models.IntegerField()),
                ('stopMessage', models.CharField(max_length=255)),
                ('emergencyMessage', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
