# Generated by Django 3.2.9 on 2021-12-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SensorApp', '0009_auto_20211230_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='ultrasonicsensor',
            name='name',
            field=models.CharField(default='HC-SR04', max_length=100),
        ),
    ]
