# Generated by Django 3.2.9 on 2021-12-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SensorApp', '0010_ultrasonicsensor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='camerasensor',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
