# Generated by Django 3.2.9 on 2021-12-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SensorApp', '0011_camerasensor_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camerasensor',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='lcdsensor',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ultrasonicsensor',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
