# Generated by Django 3.2.10 on 2022-01-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SensorApp', '0013_auto_20220102_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='lcdsensor',
            name='warningMessage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
