# Generated by Django 3.2.9 on 2022-01-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SensorApp', '0014_lcdsensor_warningmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camerasensor',
            name='pin',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lcdsensor',
            name='pin',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ultrasonicsensor',
            name='pin',
            field=models.CharField(max_length=100),
        ),
    ]
